# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    #path to the directory where the elements uploaded are stored
    files_directory: '%kernel.project_dir%/public/uploads/'
    ##parameters for the cookies and the token used to authenticate a user
    #secret string used as a key to encrypt the cookie before give them to the browser
    jwt_secret: '%env(JWT_SECRET)%'
    jwt_domain: '%env(JWT_DOMAIN)%'
    jwt_path: '%env(JWT_PATH)%'
    jwt_access_name: '%env(JWT_ACCESS_NAME)%'
    jwt_refresh_name: '%env(JWT_REFRESH_NAME)%'

    ##parameters for the recording of entity object
    refuel_refuel_name: '%env(REFUEL_REFUEL_NAME)%'
    refuel_refuels_name: '%env(REFUEL_REFUELS_NAME)%'
    refuel_volume_name: '%env(REFUEL_VOLUME_NAME)%'
    refuel_codecard_name: '%env(REFUEL_CODECARD_NAME)%'
    refuel_codedriver_name: '%env(REFUEL_CODEDRIVER_NAME)%'
    refuel_system_name: '%env(REFUEL_SYSTEM_NAME)%'
    refuel_date_name: '%env(REFUEL_DATE_NAME)%'
    refuel_stationlocation_name: '%env(REFUEL_STATIONLOCATION_NAME)%'
    refuel_mileage_name: '%env(REFUEL_MILEAGE_NAME)%'
    refuel_product_name: '%env(REFUEL_PRODUCT_NAME)%'
    limit: '%env(LIMIT)%'

    ##parameters for the recording of user entity object
    user_user_name: '%env(USER_USER_NAME)%'
    user_login_name: '%env(USER_LOGIN_NAME)%'
    user_email_name: '%env(USER_EMAIL_NAME)%'
    user_password_name: '%env(USER_PASSWORD_NAME)%'
    user_isadmin_name: '%env(USER_ISADMIN_NAME)%'
    user_homeagency_name: '%env(USER_HOMEAGENCY_NAME)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%files_directory%'

    App\DataFixtures\DataFixture:
        arguments:
            $targetDirectory: '%files_directory%'

    #Service for the security of the app
    App\Security\JWTAuthenticator:
        arguments:
            $jwt_secret: '%jwt_secret%'
            $jwt_domain: '%jwt_domain%'
            $jwt_path: '%jwt_path%'
            $jwt_access_name: '%jwt_access_name%'
            $jwt_refresh_name: '%jwt_refresh_name%'

    App\Security\JWTRefreshAuthenticator:
        arguments:
            $jwt_secret: '%jwt_secret%'
            $jwt_domain: '%jwt_domain%'
            $jwt_path: '%jwt_path%'
            $jwt_access_name: '%jwt_access_name%'
            $jwt_refresh_name: '%jwt_refresh_name%'

    App\Security\LoginAuthenticator:
        arguments:
            $jwt_secret: '%jwt_secret%'
            $jwt_domain: '%jwt_domain%'
            $jwt_path: '%jwt_path%'
            $jwt_access_name: '%jwt_access_name%'
            $jwt_refresh_name: '%jwt_refresh_name%'
            $user_login_name: '%user_login_name%'
            $user_password_name: '%user_password_name%'

    App\Controller\SecurityController:
        arguments:
            $jwt_secret: '%jwt_secret%'
            $jwt_domain: '%jwt_domain%'
            $jwt_path: '%jwt_path%'
            $jwt_access_name: '%jwt_access_name%'
            $jwt_refresh_name: '%jwt_refresh_name%'

    ##Service for the refuel management
    App\Controller\RefuelController:
        arguments:
            $refuel_volume_name: '%refuel_volume_name%'
            $refuel_codecard_name: '%refuel_codecard_name%'
            $refuel_codedriver_name: '%refuel_codedriver_name%'
            $refuel_system_name: '%refuel_system_name%'
            $refuel_date_name: '%refuel_date_name%'
            $refuel_stationlocation_name: '%refuel_stationlocation_name%'
            $refuel_mileage_name: '%refuel_mileage_name%'
            $refuel_product_name: '%refuel_product_name%'
            $refuel_refuels_name: '%refuel_refuels_name%'
            $refuel_refuel_name: '%refuel_refuel_name%'
            $limit: '%limit%'

    ##Service for the user management
    App\Controller\UserController:
        arguments:
            $user_user_name: '%user_user_name%'
            $user_login_name: '%user_login_name%'
            $user_email_name: '%user_email_name%'
            $user_password_name: '%user_password_name%'
            $user_isadmin_name: '%user_isadmin_name%'
            $user_homeagency_name: '%user_homeagency_name%'